name: CircloApp CI

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release

      - name: Publish API
        run: dotnet publish src/CircloApp.API/CircloApp.API.csproj -c Release -o publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: circloapp-api
          path: publish/