<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CircloApp.Domain\CircloApp.Domain.csproj" />
    <ProjectReference Include="..\CircloApp.Shared\CircloApp.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Features\Authentication\VerifyOtp\" />
    <Folder Include="Features\Authentication\Register\" />
    <Folder Include="Mappings\" />
    <Folder Include="DTOs\" />
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
